# Generated by Django 3.2.7 on 2023-01-04 03:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_slide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_slide_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
