# Generated by Django 3.2.7 on 2023-01-04 21:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_slide', '0003_auto_20230104_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_slide_photo',
            name='file',
        ),
        migrations.AddField(
            model_name='about_slide_photo',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
