# Generated by Django 3.2.7 on 2023-01-05 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_slide', '0004_auto_20230104_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
