# Generated by Django 3.2.7 on 2023-01-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_slide', '0005_delete_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_slide_photo',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=15, verbose_name='Name'),
        ),
    ]
